url: https://iammanchanda.github.io/creative-bootstrap/
gems:
  - jekyll-seo-tag
collections:
  portfolio:
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
permalink: /blogs/:year/:month/:day/:title/