url: https://iammanchanda.github.io
gems:
  - jekyll-seo-tag
  - jekyll-feed
collections:
  portfolio:
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
permalink: /blogs/:year/:month/:day/:title/